name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build React Docker image
      run: docker build frontend -t ${{ secrets.DOCKER_USERNAME }}/frontend

    - name: Build FastAPI Docker image
      run: docker build backend -t ${{ secrets.DOCKER_USERNAME }}/backend

    - name: Push Docker images
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_USERNAME }} &&
         docker push ${{ secrets.DOCKER_USERNAME }}/frontend && docker push ${{ secrets.DOCKER_USERNAME }}/backend
